#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Create secret
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: operator_name
      prompt: Enter the operator name. This can be found under the "labels" field in the suboperator pod
      private: false
    - name: ssh_key
      prompt: Enter the local path to your private SSH Key for this endpoint
      private: false
    - name: username
      prompt: Enter you SSH Username for this endpoint
      private: false
    - name: passphrase
      prompt: Enter the passphrase for the SSH Key for this endpoint (Press Enter to skip)
      private: true
    - name: secret_name
      prompt: Enter the name of the secret to create
      private: false

  tasks:
    - name: Cluster setup
      ansible.builtin.include_role:
        name: cluster_setup

    - name: Get SubOperator Pod Name
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ target_namespace }}"
        label_selectors:
          - "operator-name = {{ operator_name }}"
      register: suboperator_pod_results

    - name: Copy ssh key block
      block:
        - name: Copy ssh key to suboperator pod
          ansible.builtin.command: "oc cp {{ ssh_key }} {{ suboperator_pod_results['resources'][0]['metadata']['namespace'] }}/{{ suboperator_pod_results['resources'][0]['metadata']['name'] }}:/tmp/ssh_key"

        - name: Create secret with passphrase
          ansible.builtin.command: "oc exec -n {{ target_namespace }} -c {{ suboperator_pod_results['resources'][0]['spec']['containers'][0]['name'] }} {{ suboperator_pod_results['resources'][0]['metadata']['name'] }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -u {{ username }} -s {{ssh_key}} -p {{ passphrase }}"
          when: passphrase != ""

        - name: Create secret without passphrase
          ansible.builtin.command: "oc exec -n {{ target_namespace }} -c {{ suboperator_pod_results['resources'][0]['spec']['containers'][0]['name'] }} {{ suboperator_pod_results['resources'][0]['metadata']['name'] }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -u {{ username }} -s /tmp/ssh_key --namespace kberkos-dev"
          when: passphrase == ""

      always:
        - name: Delete ssh key in suboperator pod
          ansible.builtin.command: "oc exec -n {{ target_namespace }} {{ suboperator_pod_results['resources'][0]['metadata']['name'] }} -- rm /tmp/ssh_key"
