#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Create operator-config.yml file
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Set local directory
      ansible.builtin.set_fact:
        local_directory: "{{ lookup('env', 'PWD') if filepath is undefined else filepath }}"

    - name: Locate existing operator-config.yml
      ansible.builtin.find:
        paths: "{{ local_directory }}"
        patterns: 'operator-config.yml,operator-config.yaml'
      register: oc_file_results

    - name: Validate if operator-config already exists
      ansible.builtin.fail:
        msg: "operator-config.yml already exists in current directory"
      when: oc_file_results.files | length > 0

    - name: Create operator-config.yml
      ansible.builtin.include_role:
        name: create_operator_config
      vars:
        path: "{{ local_directory }}"
