##############################################################################
# Copyright 2023 IBM Corp. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##############################################################################

---
- name: Delete Operator
  hosts: localhost
  connection: local
  gather_facts: false
    
  tasks:
  - name: Set local directory
    set_fact: 
        localDirectory: "{{ lookup('env', 'PWD') if filepath is undefined else filepath }}"

  - name: Prereq Validation
    include_role:
      name: pre_check
    vars:
        path: "{{ localDirectory }}"

  - name: Get SubOperatorConfig
    k8s_info:
      api_version: zoscb.ibm.com/v2beta2
      kind: SubOperatorConfig
      namespace: "{{ namespace }}"
      label_selectors:
        - "operator-name = {{ operatorName }}"
    register: soc_results

  - name: Validate SubOperatorConfig exists
    debug:
      msg: "SubOperatorConfig doesn't exist or multiple SubOperatorConfigs listed in namespace"
    when: soc_results.resources | length == 0 or soc_results.resources | length > 1

  - name: Set subOperatorConfig exists flag
    set_fact:
      socExists: "{{ true if soc_results.resources | length == 1 else false }}"

  - name: Get mapped OperatorCollection
    k8s_info:
      api_version: zoscb.ibm.com/v2beta2
      kind: OperatorCollection
      name: "{{ soc_results.resources[0].spec.operatorCollection }}"
      namespace: "{{ namespace }}"
    register: oc_results
    when: socExists is true

  - name: Remove OperatorCollection finalizer
    kubernetes.core.k8s_json_patch:
      api_version: zoscb.ibm.com/v2beta2
      kind: OperatorCollection
      namespace: "{{ namespace }}"
      name: "{{ oc_results.resources[0].metadata.name }}"
      patch:
        - op: replace
          path: /metadata/finalizers
          value: []
    when: socExists is true

  - name: Remove OperatorCollection
    k8s:
      state: absent
      api_version: zoscb.ibm.com/v2beta2
      kind: OperatorCollection
      namespace: "{{ namespace }}"
      name: "{{ oc_results.resources[0].metadata.name }}"
    when: socExists is true

  - name: Validate SubOperatorConfig has been removed
    k8s:
      state: absent
      api_version: zoscb.ibm.com/v2beta2
      kind: SubOperatorConfig
      namespace: "{{ namespace }}"
      name: "{{ soc_results.resources[0].metadata.name }}"
      wait: yes
      wait_sleep: 5
      wait_timeout: 140
    when: socExists is true

  - name: Remove Credential Secret
    k8s:
      state: absent
      kind: Secret
      namespace: "{{ namespace }}"
      name: "{{ item.credentialName }}"
    with_items: "{{ soc_results.resources[0].spec.mapping[0].zosendpoints }}"
    when: socExists is true
    ignore_errors: true