#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Upload new collection and redeploy operator
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Set local directory
      ansible.builtin.set_fact:
        local_directory: "{{ lookup('env', 'PWD') if filepath is undefined else filepath }}"

    - name: Prereq Validation
      ansible.builtin.include_role:
        name: pre_check
      vars:
        path: "{{ local_directory }}"

    - name: Build Collection
      ansible.builtin.include_role:
        name: build_collection
      vars:
        path: "{{ local_directory }}"

    - name: Get SubOperatorConfig
      kubernetes.core.k8s_info:
        api_version: zoscb.ibm.com/v2beta2
        kind: SubOperatorConfig
        namespace: "{{ target_namespace }}"
        label_selectors:
          - "operator-name = {{ operator_name }}"
      register: soc_results

    - name: Validate SubOperatorConfig exists
      ansible.builtin.fail:
        msg: "SubOperatorConfig doesn't exist or multiple SubOperatorConfigs listed in namespace"
      when: soc_results.resources | length == 0 or soc_results.resources | length > 1

    - name: Get mapped OperatorCollection
      kubernetes.core.k8s_info:
        api_version: zoscb.ibm.com/v2beta2
        kind: OperatorCollection
        name: "{{ soc_results.resources[0].spec.operatorCollection }}"
        namespace: "{{ target_namespace }}"
      register: oc_results

    - name: Validate OperatorCollection exists
      ansible.builtin.fail:
        msg: "OperatorCollection doesn't exist"
      when: oc_results.resources | length == 0

    - name: Remove OperatorCollection finalizer
      kubernetes.core.k8s_json_patch:
        api_version: zoscb.ibm.com/v2beta2
        kind: OperatorCollection
        namespace: "{{ target_namespace }}"
        name: "{{ oc_results.resources[0].metadata.name }}"
        patch:
          - op: replace
            path: /metadata/finalizers
            value: []

    - name: Remove OperatorCollection
      kubernetes.core.k8s:
        state: absent
        api_version: zoscb.ibm.com/v2beta2
        kind: OperatorCollection
        namespace: "{{ target_namespace }}"
        name: "{{ oc_results.resources[0].metadata.name }}"

    - name: Validate SubOperatorConfig has been removed
      kubernetes.core.k8s:
        state: absent
        api_version: zoscb.ibm.com/v2beta2
        kind: SubOperatorConfig
        namespace: "{{ target_namespace }}"
        name: "{{ soc_results.resources[0].metadata.name }}"
        wait: true
        wait_sleep: 5
        wait_timeout: 140

    - name: Set OperatorCollection name
      ansible.builtin.set_fact:
        operatorcollection_name: "{{ operator_name + '.' + operator_domain + '.' + operator_version }}"

    - name: Create OperatorCollection
      ibm.operator_collection_sdk.oc_operatorcollection:
        state: present
        name: "{{ operatorcollection_name }}"
        namespace: "{{ target_namespace }}"
        skipSignatureVerification: true
        collection_src: "{{ local_directory }}/local/builds/{{operator_version}}/{{operator_domain}}-{{operator_name}}-{{operator_version}}.tar.gz"

    - name: Validate OperatorCollection installed successfully
      kubernetes.core.k8s_info:
        api_version: zoscb.ibm.com/v2beta2
        kind: OperatorCollection
        name: "{{ operatorcollection_name }}"
        namespace: "{{ target_namespace }}"
      register: updated_oc_results
      until: "updated_oc_results.resources[0].status.phase is defined and updated_oc_results.resources[0].status.phase == 'Successful'"
      retries: 5
      delay: 5

    - name: Create SubOperatorConfig
      ibm.operator_collection_sdk.oc_suboperatorconfig:
        state: present
        name: "{{ operatorcollection_name }}-soc"
        namespace: "{{ target_namespace }}"
        credentialType: "{{ soc_results.resources[0].spec.credentialType }}"
        endpointMapping: "{{ soc_results.resources[0].spec.mapping }}"
        collection_name: "{{ operatorcollection_name }}"

    - name: Validate SubOperatorConfig installed successfully
      kubernetes.core.k8s_info:
        api_version: zoscb.ibm.com/v2beta2
        kind: SubOperatorConfig
        name: "{{ operatorcollection_name }}-soc"
        namespace: "{{ target_namespace }}"
      register: updated_soc_results
      until: "updated_soc_results.resources[0].status.phase is defined and updated_soc_results.resources[0].status.phase == 'Successful'"
      retries: 30
      delay: 5
