#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Redeploy Ansible Collection to existing operator
  hosts: localhost
  connection: local
  gather_facts: false
    
  tasks:
  - name: Set local directory
    set_fact: 
        localDirectory: "{{ lookup('env', 'PWD') if filepath is undefined else filepath }}"  

  - name: Prereq Validation
    include_role:
      name: pre_check
    vars:
        path: "{{ localDirectory }}"

  - name: Build Collection
    include_role:
      name: build_collection
    vars:
        path: "{{ localDirectory }}"

  - name: Upload collection to manager pod
    include_role:
      name: upload_collection_to_manager
    static: no
    vars:
        path: "{{ localDirectory }}"
        ns: "{{ targetNamespace }}"

  - name: Restart suboperator pod
    include_role:
      name: restart_suboperator_pod
    vars:
      ns: "{{ targetNamespace }}"