#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Redeploy Ansible Collection to existing operator
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print filepath variable
      ansible.builtin.debug:
        msg: "{{ filepath }}"

    - name: Set local directory
      ansible.builtin.set_fact:
        local_directory: "{{ lookup('env', 'PWD') if filepath is undefined else filepath }}"

    - name: Print local_directory variable
      ansible.builtin.debug:
        msg: "{{ local_directory }}"

    - name: Prereq Validation
      ansible.builtin.include_role:
        name: pre_check
      vars:
        path: "{{ local_directory }}"

    - name: Build Collection
      ansible.builtin.include_role:
        name: build_collection
      vars:
        path: "{{ local_directory }}"

    - name: Upload collection to manager pod
      ansible.builtin.include_role:
        name: upload_collection_to_manager
      vars:
        path: "{{ local_directory }}"
        namespace: "{{ target_namespace }}"

    - name: Restart suboperator pod
      ansible.builtin.include_role:
        name: restart_suboperator_pod
      vars:
        namespace: "{{ target_namespace }}"
