#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

#########################################################################
# This role is the bare minimum for running playbooks against a clister.
# Ensure that the user is logged into the cluster, and store namespace 
# for future tasks
#########################################################################

---
- name: Validate OCP cluster authorization
  ansible.builtin.command: oc project
  register: oc_project_output
  ignore_errors: true

- name: Cluster login prompt
  ansible.builtin.fail:
    msg: "Please log into an OCP cluster via the command line. (example: oc login --token=<token> --server=<server_url>)"
  when: oc_project_output.rc != 0

- name: Get namespace
  ansible.builtin.command: oc config view --minify -o 'jsonpath={..namespace}'
  register: namespace_output

- name: Set namespace variable
  ansible.builtin.set_fact:
    target_namespace: "{{ namespace_output.stdout if ocpnamespace is undefined else ocpnamespace }}"
