#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Verify
  hosts: all
  connection: local
  gather_facts: false
  vars:
    ocpnamespace: "{{ ocpNamespace | lower | replace('_','-') | replace('/','-') }}"

  tasks:
    - name: Validate default secret 
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Secret
        name: "{{ secret_name }}"
        namespace: "{{ ocpnamespace }}"
      register: default_secret_results
      until: "default_secret_results.resources[0].status.phase == 'Succeeded'"
      retries: 30
      delay: 5
      no_log: true

    - name: Assert default secret
      ansible.builtin.assert:
        that: 
          -  default_secret_results.data != ""
          -  default_secret_results.type == ""
    
    - name: Validate passphrase secret 
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Secret
        name: "passphrase_secret"
        namespace: "{{ ocpnamespace }}"
      register: passphrase_secret_results
      until: "passphrase_secret_results.resources[0].status.phase == 'Succeeded'"
      retries: 30
      delay: 5
      no_log: true

    - name: Assert passphrase secret
      ansible.builtin.assert:
        that: 
          -  passphrase.data != ""
          -  passphrase.type == ""