#
# Copyright 2024 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Clean test environment
  import_playbook: ../cluster_clean.yml

- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Remove local build
      ansible.builtin.file:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../examples/racf-operator/local"
        state: absent