##############################################################################
# Copyright 2023 IBM Corp. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##############################################################################

---
- name: Converge
  hosts: all
  connection: local
  gather_facts: false
    
  tasks:
    - name: Create Namespace
      k8s:
        state: present
        definition:
          kind: Namespace
          metadata:
            name: "{{ ocpNamespace }}"

    - name: Create OperatorGroup
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: "{{ ocpNamespace }}"
            namespace: "{{ ocpNamespace }}"
          spec:
            targetNamespaces:
              - "{{ ocpNamespace }}"
            upgradeStrategy: Default


    - name: Create Subscripton
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: "{{ subscriptionName }}"
            namespace: "{{ ocpNamespace }}"
          spec:
            channel: v2.2
            installPlanApproval: Automatic
            name: ibm-zoscb
            source: ibm-operator-catalog
            sourceNamespace: openshift-marketplace
            startingCSV: ibm-zoscb.v2.2.0

    - name: Validate Subscription installed successfully
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ subscriptionName }}"
        namespace: "{{ ocpNamespace }}"
      register: subscription_results
      until: "subscription_results.resources[0].status.installedCSV is defined and subscription_results.resources[0].status.currentCSV"
      retries: 30
      delay: 5

    - name: Validate CSV installed successfully
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ subscription_results.resources[0].status.installedCSV }}"
        namespace: "{{ ocpNamespace }}"
      register: csv_results
      until: "csv_results.resources[0].status.phase is defined and csv_results.resources[0].status.phase == 'Succeeded'"
      retries: 30
      delay: 5

    - name: Create ZosCloudBoker
      k8s:
        state: present
        definition:
          apiVersion: zoscb.ibm.com/v2beta1
          kind: ZosCloudBroker
          metadata:
            name: "{{ zoscloudbrokerName }}"
            namespace: "{{ ocpNamespace }}"
          spec:
            catalogResources: {}
            license:
              accept: true
            logLevel: trace
            managerResources: {}
            storage:
              configure: false
              enabled: false
              size: 5Gi
              volumeMode: Filesystem
            uiResources: {}

    - name: Validate ZosCloudBroker installed successfully
      k8s_info:
        api_version: zoscb.ibm.com/v2beta1
        kind: ZosCloudBroker
        name: "{{ zoscloudbrokerName }}"
        namespace: "{{ ocpNamespace }}"
      register: zoscb_results
      until: "zoscb_results.resources[0].status.phase == 'Successful'"
      retries: 30
      delay: 5


- import_playbook: ../../create_operator.yml
  vars:
    filepath: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../examples/racf-operator"

- import_playbook: ../../redeploy_operator.yml
  vars:
    filepath: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../examples/racf-operator"

- import_playbook: ../../redeploy_collection.yml
  vars:
    filepath: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../examples/racf-operator"