##############################################################################
# Copyright 2023 IBM Corp. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##############################################################################

---
- name: Delete Operator
  import_playbook: ../../delete_operator.yml
  vars:
    filepath: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../examples/racf-operator"
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Delete ZosEndpoint
      k8s:
        state: absent
        api_version: zoscb.ibm.com/v2beta2
        kind: ZosEndpoint
        name: "{{ zosendpointName }}"
        namespace: "{{ ocpNamespace }}"
        wait: yes
        wait_sleep: 5
        wait_timeout: 140

    - name: Delete ZosCloudBoker
      k8s:
        state: absent
        api_version: zoscb.ibm.com/v2beta1
        kind: ZosCloudBroker
        name: "{{ zoscloudbrokerName }}"
        namespace: "{{ ocpNamespace }}"
        wait: yes
        wait_sleep: 5
        wait_timeout: 140

    - name: Delete Subscripton
      k8s:
        state: absent
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ subscriptionName }}"
        namespace: "{{ ocpNamespace }}"
        wait: yes
        wait_sleep: 5
        wait_timeout: 140

    - name: Delete OperatorGroup
      k8s:
        state: absent
        api_version: operators.coreos.com/v1
        kind: OperatorGroup
        name: "{{ ocpNamespace }}"
        namespace: "{{ ocpNamespace }}"


    - name: Delete Namespace
      k8s:
        state: absent
        kind: Namespace
        name: "{{ ocpNamespace }}"
        wait: yes
        wait_sleep: 5
        wait_timeout: 140

    - name: Remove local build
      ansible.builtin.file:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../examples/racf-operator/local"
        state: absent

