#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
- name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_native: true
      
  ## extra-vars needed to bypass vars_prompts
  ansible_args:
    - --extra-vars=@molecule/create_redeploy_delete_operator/extra_vars.yaml
  inventory:
    group_vars:
      all:
        collection_name: test_collection
        collection_namespace: ibm
        subscription_name: ibm-zoscb
        zoscloudbroker_name: zoscloudbroker
        ocpNamespace: ${OCP_NAMESPACE:-molecule}
        zosendpoint_name: ibmcloud-vm
        secret_name: "test-secret"
        openshift_token: ${OPENSHIFT_TOKEN}
        openshift_server: ${OPENSHIFT_SERVER}
        zoscb_release: ${ZOSCB_RELEASE:-ibm-zoscb.v2.2.5}
        skip_credential_check: true
scenario:
  test_sequence:
    - prepare
    - destroy
    - converge
    - verify
    - destroy
verifier:
  name: ansible