#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
- name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_native: true
      
  ## extra-vars needed to bypass vars_prompts
  ansible_args:
    - --extra-vars=@molecule/default/extra_vars.yaml
  inventory:
    group_vars:
      all:
        collectionName: test_collection
        collectionNamespace: ibm
        subscriptionName: ibm-zoscb
        zoscloudbrokerName: zoscloudbroker
        ocpNamespace: molecule
        zosendpointName: ibmcloud-vm
scenario:
  test_sequence:
    - destroy
    - converge
    - verify
    - destroy
verifier:
  name: ansible