#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Verify
  hosts: all
  connection: local
  gather_facts: false
  vars:
    ocpNamespace: "{{ ocpNamespace | lower | replace('_','-') | replace('/','-') }}"
    
  tasks:
    - name: Validate ZosEndpoint
      k8s_info:
        api_version: zoscb.ibm.com/v2beta2
        kind: ZosEndpoint
        name: "{{ zosendpointName }}"
        namespace: "{{ ocpNamespace }}"
      register: zosendpoint_results
      
    - name: Assert ZosEndpoint configuration
      ansible.builtin.assert:
        that: 
          -  zosendpoint_results.resources[0].status.phase == 'Successful'
          -  zosendpoint_results.resources[0].status.suboperatorconfigs | length == 1

    - name: Validate SubOperatorConfig
      k8s_info:
        api_version: zoscb.ibm.com/v2beta2
        kind: SubOperatorConfig
        name: "{{ zosendpoint_results.resources[0].status.suboperatorconfigs[0].name }}"
        namespace: "{{ ocpNamespace }}"
      register: suboperatorconfig_results

    - name: Assert SubOperatorConfig configuration
      ansible.builtin.assert:
        that: 
          -  suboperatorconfig_results.resources[0].spec.credentialType == 'personal'
          -  suboperatorconfig_results.resources[0].spec.mapping[0].namespace == '{{ ocpNamespace }}'
          -  suboperatorconfig_results.resources[0].spec.mapping[0].zosendpoints[0].name == '{{ zosendpointName }}'
          -  suboperatorconfig_results.resources[0].spec.mapping[0].zosendpoints[0].credentialName is undefined
          -  suboperatorconfig_results.resources[0].spec.operatorCollection is defined
          -  suboperatorconfig_results.resources[0].status.phase == 'Successful'
          -  suboperatorconfig_results.resources[0].status.clusterserviceversion is defined
          -  suboperatorconfig_results.resources[0].status.customresourcedefinition | length > 0
          -  suboperatorconfig_results.resources[0].status.packages is defined

    - name: Validate OperatorCollection
      k8s_info:
        api_version: zoscb.ibm.com/v2beta2
        kind: OperatorCollection
        name: "{{ suboperatorconfig_results.resources[0].spec.operatorCollection }}"
        namespace: "{{ ocpNamespace }}"
      register: operatorcollection_results

    - name: Assert OperatorCollection configuration
      ansible.builtin.assert:
        that: 
          -  operatorcollection_results.resources[0].spec.skipSignatureVerification is true
          -  operatorcollection_results.resources[0].status.config.collectionPath is defined
          -  operatorcollection_results.resources[0].status.phase == 'Successful'
          -  operatorcollection_results.resources[0].status.subOperatorConfigMappingStatus | length == 1

    - name: Validate CSV
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ suboperatorconfig_results.resources[0].status.clusterserviceversion.metadata.name  }}"
        namespace: "{{ ocpNamespace }}"
      register: csv_results

    - name: Assert CSV configuration
      ansible.builtin.assert:
        that: 
          -  csv_results.resources[0].status.phase == 'Succeeded'