#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.2.0 or later
###############################################################################

- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  vars_files:
    - vars/all.yml
  environment: "{{ environment_vars }}"

  tasks:
    - name: Add user to z/OS system
      include_role:
        name: add-zos-user
