#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Get SubOperator Pod Name
  k8s_info:
    kind: Pod
    namespace: "{{ ns }}"
    label_selectors:
      - "operator-name = {{ operatorName }}"
  register: suboperator_pod_results

- name: Validate suboperator pod exists
  fail:
    msg: "Suboperator pod doesn't exist"
  when: suboperator_pod_results.resources | length == 0

- name: Restart suboperator pod
  k8s:
    state: absent
    kind: Pod
    name: "{{ suboperator_pod_results.resources[0].metadata.name }}"
    namespace: "{{ ns }}"
  with_items: "{{ suboperator_pod_results.resources }}"
  when: item.metadata.deletionTimestamp is not defined
  no_log: true