#
# Copyright 2024 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Test Environment Setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get Virtual Env path if it exists
      ansible.builtin.command: echo $VIRTUAL_ENV
      register: venv_path

    - name: Install Dependencies when in a Virtual Env
      pip:
        virtualenv: "{{ venv_path.stdout_lines[0] }}"
        name:
          - openshift
          - pyyaml
          - kubernetes 
      when: 
        - venv_path.stdout_lines | length > 0
        - venv_path.stdout_lines[0] != "$VIRTUAL_ENV"

    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          metadata:
            name: "{{ ocpnamespace }}"

    - name: Create OperatorGroup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: "{{ ocpnamespace }}"
            namespace: "{{ ocpnamespace }}"
          spec:
            targetNamespaces:
              - "{{ ocpnamespace }}"
            upgradeStrategy: Default

    - name: Create Subscripton
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: "{{ subscription_name }}"
            namespace: "{{ ocpnamespace }}"
          spec:
            channel: v2.2
            installPlanApproval: Automatic
            name: ibm-zoscb
            source: ibm-operator-catalog
            sourceNamespace: openshift-marketplace
            startingCSV: "{{ zoscb_release }}"

    - name: Validate Subscription installed successfully
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ subscription_name }}"
        namespace: "{{ ocpnamespace }}"
      register: subscription_results
      until: "subscription_results.resources[0].status.installedCSV is defined and subscription_results.resources[0].status.currentCSV"
      retries: 30
      delay: 5

    - name: Validate CSV installed successfully
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ subscription_results.resources[0].status.installedCSV }}"
        namespace: "{{ ocpnamespace }}"
      register: csv_results
      until: "csv_results.resources[0].status.phase is defined and csv_results.resources[0].status.phase == 'Succeeded'"
      retries: 30
      delay: 5

    - name: Create ZosCloudBoker
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: zoscb.ibm.com/v2beta1
          kind: ZosCloudBroker
          metadata:
            name: "{{ zoscloudbroker_name }}"
            namespace: "{{ ocpnamespace }}"
          spec:
            catalogResources: {}
            license:
              accept: true
            logLevel: trace
            managerResources: {}
            storage:
              configure: false
              enabled: false
              size: 5Gi
              volumeMode: Filesystem
            uiResources: {}

    - name: Validate ZosCloudBroker installed successfully
      kubernetes.core.k8s_info:
        api_version: zoscb.ibm.com/v2beta1
        kind: ZosCloudBroker
        name: "{{ zoscloudbroker_name }}"
        namespace: "{{ ocpnamespace }}"
      register: zoscb_results
      until: "zoscb_results.resources[0].status.phase == 'Successful'"
      retries: 30
      delay: 5
