#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Set up test environment
  import_playbook: ../cluster_setup.yml

- name: Converge
  import_playbook: ../../create_operator.yml
  vars:
    filepath: "{{ operator_path }}"
