#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
- name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_native: true
  playbooks:
    cleanup: cleanup.yml
      
  ## extra-vars needed to bypass vars_prompts
  ansible_args:
    - --extra-vars=@molecule/create_operator_local/extra_vars.yaml
  inventory:
    group_vars:
      all:
        collection_name: test_collection
        collection_namespace: ibm
        subscription_name: ibm-zoscb
        zoscloudbroker_name: zoscloudbroker
        ocpnamespace: "{{ '${OCP_NAMESPACE:-molecule}' | lower | regex_replace('[^-a-zA-Z0-9]','-') }}"
        operator_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../examples/racf-operator"
        zosendpoint_name: ibmcloud-vm
        openshift_token: ${OPENSHIFT_TOKEN}
        openshift_server: ${OPENSHIFT_SERVER}
        zoscb_release: ${ZOSCB_RELEASE:-ibm-zoscb.v2.2.6}
scenario:
  test_sequence:
    - prepare
    - destroy
    - converge
    - verify
    - destroy
verifier:
  name: ansible