---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Copy example Racf operator directory
      ansible.builtin.copy:
        src: "{{ operator_path }}"
        dest: "{{ test_operator_path }}"

    - name: Test role "Build Collection"
      ansible.builtin.include_role:
        name: ../../roles/build_collection
        tasks_from: main.yml
      vars:
        path: "{{ test_operator_path }}"
