#
# Copyright 2024 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Clean test environment
  import_playbook: ../cluster_clean.yml

- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Delete test Racf Collection
      ansible.builtin.file:
        path: "{{ test_operator_path }}"
        state: absent