#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Locate galaxy.yml file
  ansible.builtin.find:
    paths: "{{ path }}"
    patterns: 'galaxy.yml,galaxy.yaml'
  register: galaxy_file_results

- name: Validate galaxy.yml file exists in current working directory
  fail:
    msg: "Collection must be executed in same directory as galaxy.yml file"
  when: galaxy_file_results.files | length == 0

- name: Read galaxy.yml
  set_fact:
    galaxyYaml: "{{ lookup('template', '{{ galaxy_file_results.files[0].path }}')|from_yaml }}"

- name: Set operator variables
  set_fact:
    oc_name: "{{ galaxyYaml.name | lower | replace('_','-') }}"
    oc_domain: "{{ galaxyYaml.namespace | lower | replace('_','-') }}"
    oc_version: "{{ galaxyYaml.version }}"
    oc_description: "{{ galaxyYaml.description }}"

- name: Generate operator-config.yml file
  ansible.builtin.template:
    src: templates/operator-config.j2
    dest: "{{ path }}/operator-config.yml"