#
# Copyright 2023 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

---
- name: Build Collection
  ansible.builtin.command: ansible-galaxy collection build {{ path }} -f --output-path {{ path }}/local/builds/{{ operator_version }}
