baseURL = 'https://operatorcollection.io/'
languageCode = 'en-us'
title = 'IBM Operator Collection SDK Documentation'

[module]
    # uncomment line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[[menu.primary]]
name  = "Docs"
url = "/docs/"
identifier = "docs"
weight = 10

[params]

# Google Fonts
google_fonts = [
    ["IBM Plex Sans", "100, 200, 300, 400, 500, 600, 700"], 
    ["IBM Plex Mono", "100, 200, 300, 400, 500, 600, 700"]
]

sans_serif_font = "IBM Plex Sans"
secondary_font  = "IBM Plex Sans"
mono_font       = "IBM Plex Mono"

[params.footer]
copyright = "© Copyright IBM Corporation :YEAR:. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"

[params.docs] # Parameters for the /docs 'template'
title           = "IBM Operator Collection SDK Documentation"   # default html title for documentation pages/sections
repoURL         = "https://github.com/IBM/operator-collection-sdk"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
repoBranch      = "main"                              # Name of your Git repository branch

darkMode        = true                                # enable dark mode option? default false
prism           = true                                # enable syntax highlighting via Prism
editPage        = true                                # enable 'Edit this page' feature - default false
lastMod         = true                                # enable 'Last modified' date on pages - default false
lastModRelative = true                                # format 'Last modified' time as relative - default true

# ToC
toc             = true                                # enable table of contents? default is true
tocMobile       = true                                # enable table of contents in mobile view? default is true
scrollSpy       = true                                # enable scrollspy on ToC? default is true

# icons
sidebarIcons    = true                                # enable sidebar icons? default false
titleIcon       = true                                # enable front matter icon title prefix? default is false

# content navigation
breadcrumbs     = true                                # default is true
navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description
backToTop       = true                                # enable back-to-top button? default true

# front matter
descriptions    = true                                # enable front matter descriptions under content title?

# link behavior
intLinkTooltip   = true                               # Enables tooltip for internal links
extLinkNewTab    = true                               # Open external links in a new tab