# Execute Molecule Tests

name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    tags-ignore:
      - '**'
  pull_request:
    branches:    
      - main
      - v0.*
      - v1.*
  workflow_dispatch:

jobs:
  test:
    name: Test

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
        with:
          path: "${GITHUB_WORKSPACE}/ibm/operator_collection_sdk/playbooks/"

      - name: Install Python Requirements
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Perform PIP installs
        run: pip install -r ${GITHUB_WORKSPACE}/ibm/operator_collection_sdk/requirements.txt
      
      - name: Install oc cli
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'

      - name: Log into OCP
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Execute Molecule Tests
        run: |
          cd ${GITHUB_WORKSPACE}/ibm/operator_collection_sdk/playbooks
          export ANSIBLE_PYTHON_INTERPRETER="$(which python)"
          OCP_NAMESPACE=molecule-${GITHUB_REF_NAME}-${RUNNER_OS} molecule test --all